const replacements = [
    {    regex: /CORE-UA(&nbsp;)105/g, replacement:  "Quantitative Reasoning: Elementary Statistics" },
    {    regex: /CORE-UA(&nbsp;)107/g, replacement:  "Quantitative Reasoning: Prob,Stats & Decisn-Mkng" },
    {    regex: /CORE-UA(&nbsp;)109/g, replacement:  "Quantitative Reasoning: Math & Computing" },
    {    regex: /CORE-UA(&nbsp;)110/g, replacement:  "Quantitative Reasoning: Great Ideas in Mathematics" },
    {    regex: /CORE-UA(&nbsp;)111/g, replacement:  "Quantitative Reasoning: From Data to Discovery" },
    {    regex: /CORE-UA(&nbsp;)203/g, replacement:  "Physical Science: Energy & The Environment" },
    {    regex: /CORE-UA(&nbsp;)204/g, replacement:  "Physical Science: Einstein's Universe" },
    {    regex: /CORE-UA(&nbsp;)209/g, replacement:  "Physical Science: Quarks to Cosmos" },
    {    regex: /CORE-UA(&nbsp;)210/g, replacement:  "Physical Science: Molecules of Life" },
    {    regex: /CORE-UA(&nbsp;)214/g, replacement:  "Physical Science: How Things Work" },
    {    regex: /CORE-UA(&nbsp;)303/g, replacement:  "Life Science: Human Genetics" },
    {    regex: /CORE-UA(&nbsp;)306/g, replacement:  "Life Science: Brain and Behavior" },
    {    regex: /CORE-UA(&nbsp;)312/g, replacement:  "Life Science: Earth, Life & Time" },
    {    regex: /CORE-UA(&nbsp;)315/g, replacement:  "Life Science: Human Reproduction" },
    {    regex: /CORE-UA(&nbsp;)400/g, replacement:  "Texts & Ideas:" },
    {    regex: /CORE-UA(&nbsp;)403/g, replacement:  "Texts & Ideas: Antiquity & The Enlightenment" },
    {    regex: /CORE-UA(&nbsp;)404/g, replacement:  "Texts & Ideas: Antiquity & The 19th Century" },
    {    regex: /CORE-UA(&nbsp;)500/g, replacement:  "Cultures & Contexts: Topics" },
    {    regex: /CORE-UA(&nbsp;)502/g, replacement:  "Cultures & Contexts: Islamic Societies" },
    {    regex: /CORE-UA(&nbsp;)507/g, replacement:  "Cultures & Contexts: Japan" },
    {    regex: /CORE-UA(&nbsp;)510/g, replacement:  "Cultures and Contexts: Russia Between East and West" },
    {    regex: /CORE-UA(&nbsp;)514/g, replacement:  "Cultures & Contexts: Ancient Israel" },
    {    regex: /CORE-UA(&nbsp;)529/g, replacement:  "Cultures & Contexts: Contemporary Latino Cultures" },
    {    regex: /CORE-UA(&nbsp;)532/g, replacement:  "Cultures & Contexts: African Diaspora" },
    {    regex: /CORE-UA(&nbsp;)534/g, replacement:  "Cultures & Contexts: The Black Atlantic" },
    {    regex: /CORE-UA(&nbsp;)536/g, replacement:  "Cultures & Contexts: Indigenous Australia" },
    {    regex: /CORE-UA(&nbsp;)539/g, replacement:  "Cultures & Contexts: Asian / Pacific / American Cultures" },
    {    regex: /CORE-UA(&nbsp;)544/g, replacement:  "Cultures & Contexts: Spain" },
    {    regex: /CORE-UA(&nbsp;)545/g, replacement:  "Cultures & Contexts: Egypt of The Pharaohs" },
    {    regex: /CORE-UA(&nbsp;)546/g, replacement:  "Cultures & Contexts: Global Asia" },
    {    regex: /CORE-UA(&nbsp;)555/g, replacement:  "Cultures & Context: Brazil" },
    {    regex: /CORE-UA(&nbsp;)711/g, replacement:  "Expressive Culture: The Graphic Novel" },
    {    regex: /CORE-UA(&nbsp;)722/g, replacement:  "Expressive Culture: Architecture in New York Field" },
    {    regex: /CORE-UA(&nbsp;)724/g, replacement:  "Expressive Culture: Photography" },
    {    regex: /CORE-UA(&nbsp;)730/g, replacement:  "Expressive Culture: Sounds" },
    {    regex: /CORE-UA(&nbsp;)740/g, replacement:  "Expressive Culture:Performance" },
    {    regex: /CORE-UA(&nbsp;)750/g, replacement:  "Expressive Culture: Film" },
    {    regex: /CORE-UA(&nbsp;)760/g, replacement:  "Expressive Culture: Topics" },
    {    regex: /CHEM-UA(&nbsp;)120/g, replacement:  "Introduction to Modern Chemistry" },
    {    regex: /CHEM-UA(&nbsp;)125/g, replacement:  "General Chemistry I & Laboratory" },
    {    regex: /CHEM-UA(&nbsp;)126/g, replacement:  "General Chemistry II & Laboratory" },
    {    regex: /CHEM-UA(&nbsp;)129/g, replacement:  "Accelerated General Chemistry" },
    {    regex: /CHEM-UA(&nbsp;)140/g, replacement:  "Mathematics of Chemistry" },
    {    regex: /CHEM-UA(&nbsp;)210/g, replacement:  "Principles of Organic and Biological Chemistry and Laboratory" },
    {    regex: /CHEM-UA(&nbsp;)225/g, replacement:  "Organic Chemistry I & Laboratory" },
    {    regex: /CHEM-UA(&nbsp;)226/g, replacement:  "Organic Chemistry II & Laboratory" },
    {    regex: /CHEM-UA(&nbsp;)227/g, replacement:  "Majors Organic Chemistry I & Laboratory" },
    {    regex: /CHEM-UA(&nbsp;)651/g, replacement:  "Quantum Mechanics & Spectroscopy" },
    {    regex: /CHEM-UA(&nbsp;)652/g, replacement:  "Thermodynamics & Kinetics" },
    {    regex: /CHEM-UA(&nbsp;)661/g, replacement:  "Physical Chemistry Laboratory" },
    {    regex: /CHEM-UA(&nbsp;)752/g, replacement:  "Computational Chemistry" },
    {    regex: /CHEM-UA(&nbsp;)828/g, replacement:  "Structural DNA Nanotechnology" },
    {    regex: /CHEM-UA(&nbsp;)881/g, replacement:  "Biochemistry I" },
    {    regex: /CHEM-UA(&nbsp;)885/g, replacement:  "Experimental Biochem & Laboratory" },
    {    regex: /CHEM-UA(&nbsp;)911/g, replacement:  "Advanced Organic Chemistry" },
    {    regex: /CHEM-UA(&nbsp;)995/g, replacement:  "Senior Honors in Chem" },
    {    regex: /CHEM-UA(&nbsp;)997/g, replacement:  "Adv Independent Study & Research" },
    {    regex: /CSCI-UA(&nbsp;)2/g, replacement:  "Introduction to Computer Programming" },
    {    regex: /CSCI-UA(&nbsp;)4/g, replacement:  "Introduction to Web Design and Computer Principles" },
    {    regex: /CSCI-UA(&nbsp;)60/g, replacement:  "Database Design and Web Implementation" },
    {    regex: /CSCI-UA(&nbsp;)61/g, replacement:  "Web Development and Programming" },
    {    regex: /CSCI-UA(&nbsp;)101/g, replacement:  "Intro to Computer SCI" },
    {    regex: /CSCI-UA(&nbsp;)102/g, replacement:  "Data Structures" },
    {    regex: /CSCI-UA(&nbsp;)201/g, replacement:  "Computer Systems Org" },
    {    regex: /CSCI-UA(&nbsp;)202/g, replacement:  "Operating Systems" },
    {    regex: /CSCI-UA(&nbsp;)310/g, replacement:  "Basic Algorithms" },
    {    regex: /CSCI-UA(&nbsp;)380/g, replacement:  "Topics of General Interest:" },
    {    regex: /CSCI-UA(&nbsp;)472/g, replacement:  "Artificial Intelligence" },
    {    regex: /CSCI-UA(&nbsp;)480/g, replacement:  "Special Topics:" },
    {    regex: /CSCI-UA(&nbsp;)490/g, replacement:  "Spec Tpcs in Prog Lang:" },
    {    regex: /CSCI-UA(&nbsp;)520/g, replacement:  "Undergraduate Research" },
    {    regex: /CSCI-UA(&nbsp;)897/g, replacement:  "Internship in Computer Science" },
    {    regex: /CSCI-UA(&nbsp;)997/g, replacement:  "Independent Study" },
    {    regex: /CSCI-UA(&nbsp;)330/g, replacement:  "Introduction to Computer Simulation" },
    {    regex: /CSCI-UA(&nbsp;)421/g, replacement:  "Numerical Computing" },
    {    regex: /CSCI-UA(&nbsp;)453/g, replacement:  "Theory of Computation" },
    {    regex: /CSCI-UA(&nbsp;)473/g, replacement:  "Introduction to Machine Learning" },
    {    regex: /CSCI-UA(&nbsp;)521/g, replacement:  "Undergraduate Research" },
    {    regex: /CSCI-UA(&nbsp;)898/g, replacement:  "Internship in Computer Science" },
    {    regex: /CSCI-UA(&nbsp;)998/g, replacement:  "Independent Study" },
    {    regex: /MATH-UA(&nbsp;)9/g, replacement:  "Algebra and Calculus" },
    {    regex: /MATH-UA(&nbsp;)120/g, replacement:  "Discrete Mathematics" },
    {    regex: /MATH-UA(&nbsp;)121/g, replacement:  "Calculus I" },
    {    regex: /MATH-UA(&nbsp;)122/g, replacement:  "Calculus II" },
    {    regex: /MATH-UA(&nbsp;)123/g, replacement:  "Calculus III" },
    {    regex: /MATH-UA(&nbsp;)129/g, replacement:  "Honors Calculus III" },
    {    regex: /MATH-UA(&nbsp;)140/g, replacement:  "Linear Algebra" },
    {    regex: /MATH-UA(&nbsp;)144/g, replacement:  "Introduction to Computer Simulation" },
    {    regex: /MATH-UA(&nbsp;)148/g, replacement:  "Honors Linear Algebra" },
    {    regex: /MATH-UA(&nbsp;)211/g, replacement:  "Mathematics for Economics I" },
    {    regex: /MATH-UA(&nbsp;)212/g, replacement:  "Mathematics for Economics II" },
    {    regex: /MATH-UA(&nbsp;)213/g, replacement:  "Mathematics for Economics III" },
    {    regex: /MATH-UA(&nbsp;)224/g, replacement:  "Vector Analysis" },
    {    regex: /MATH-UA(&nbsp;)228/g, replacement:  "Fundamental Dynamics of Earth's Atmosphere and Climate" },
    {    regex: /MATH-UA(&nbsp;)230/g, replacement:  "Introduction to Fluid Dynamics" },
    {    regex: /MATH-UA(&nbsp;)233/g, replacement:  "Theory of Probability" },
    {    regex: /MATH-UA(&nbsp;)234/g, replacement:  "Mathematical Statistics" },
    {    regex: /MATH-UA(&nbsp;)235/g, replacement:  "Probability & Statistics" },
    {    regex: /MATH-UA(&nbsp;)240/g, replacement:  "Combinatorics" },
    {    regex: /MATH-UA(&nbsp;)250/g, replacement:  "Mathematics of Finance" },
    {    regex: /MATH-UA(&nbsp;)251/g, replacement:  "Intro to Math Modeling" },
    {    regex: /MATH-UA(&nbsp;)252/g, replacement:  "Numerical Analysis" },
    {    regex: /MATH-UA(&nbsp;)256/g, replacement:  "Computers in Medicine & Biology" },
    {    regex: /MATH-UA(&nbsp;)262/g, replacement:  "Ordinary Diff Equations" },
    {    regex: /MATH-UA(&nbsp;)263/g, replacement:  "Partial Diff Equations" },
    {    regex: /MATH-UA(&nbsp;)264/g, replacement:  "Chaos & Dynamical Systems" },
    {    regex: /MATH-UA(&nbsp;)282/g, replacement:  "Functions of a Complex Variable" },
    {    regex: /MATH-UA(&nbsp;)325/g, replacement:  "Analysis" },
    {    regex: /MATH-UA(&nbsp;)329/g, replacement:  "Honors Analysis II" },
    {    regex: /MATH-UA(&nbsp;)343/g, replacement:  "Algebra" },
    {    regex: /MATH-UA(&nbsp;)349/g, replacement:  "Honors Algebra II" },
    {    regex: /MATH-UA(&nbsp;)375/g, replacement:  "Topology" },
    {    regex: /MATH-UA(&nbsp;)377/g, replacement:  "Differential Geometry" },
    {    regex: /MATH-UA(&nbsp;)394/g, replacement:  "Senior Honors II" },
    {    regex: /MATH-UA(&nbsp;)998/g, replacement:  "Independent Study" },
    {    regex: /FREN-UA(&nbsp;)1/g, replacement:  "Elemen French Level I" },
    {    regex: /FREN-UA(&nbsp;)2/g, replacement:  "Elem French Level II" },
    {    regex: /FREN-UA(&nbsp;)10/g, replacement:  "Intens Elementary French" },
    {    regex: /FREN-UA(&nbsp;)11/g, replacement:  "Intermediate French I" },
    {    regex: /FREN-UA(&nbsp;)12/g, replacement:  "Intermediate French II" },
    {    regex: /FREN-UA(&nbsp;)20/g, replacement:  "Intens Intermed French" },
    {    regex: /FREN-UA(&nbsp;)27/g, replacement:  "Living in French in North America: An Immersion Program in New England and Quebec" },
    {    regex: /FREN-UA(&nbsp;)30/g, replacement:  "French Grammar and Composition." },
    {    regex: /FREN-UA(&nbsp;)101/g, replacement:  "Spoken Contemp French I" },
    {    regex: /FREN-UA(&nbsp;)102/g, replacement:  "Advanced Conversation" },
    {    regex: /FREN-UA(&nbsp;)103/g, replacement:  "French Phonetics" },
    {    regex: /FREN-UA(&nbsp;)105/g, replacement:  "Written Contemporary French" },
    {    regex: /FREN-UA(&nbsp;)107/g, replacement:  "French Translation" },
    {    regex: /FREN-UA(&nbsp;)108/g, replacement:  "French: Advanced Techniques of Translation" },
    {    regex: /FREN-UA(&nbsp;)110/g, replacement:  "Business French" },
    {    regex: /FREN-UA(&nbsp;)111/g, replacement:  "Creative Writing in French" },
    {    regex: /FREN-UA(&nbsp;)121/g, replacement:  "Rdngs in French Lit II: 1800-Present" },
    {    regex: /FREN-UA(&nbsp;)145/g, replacement:  "French: Approaches to Francophone Literature" },
    {    regex: /FREN-UA(&nbsp;)150/g, replacement:  "French: Versailles" },
    {    regex: /FREN-UA(&nbsp;)771/g, replacement:  "The French Canon: Proust" },
    {    regex: /FREN-UA(&nbsp;)774/g, replacement:  "The French Canon: Beckett" },
    {    regex: /FREN-UA(&nbsp;)829/g, replacement:  "Theatre in The French Tradition" },
    {    regex: /FREN-UA(&nbsp;)868/g, replacement:  "Topics in French Lit" },
    {	 regex:  /FREN-UA(&nbsp;)904/g, replacement:  "French News, with Coffee"},
    {    regex:   /FREN-UA(&nbsp;)905/g, replacement:  "Machines à écrire"},
    {    regex:   /FREN-UA(&nbsp;)968/g, replacement:  "Topics:"},
    {    regex:   /FREN-UA(&nbsp;)981/g, replacement:  "Internship in French"},
    {    regex:   /FREN-UA(&nbsp;)992/g, replacement:  "Senior Seminar"},
    {    regex:   /FREN-UA(&nbsp;)995/g, replacement:  "Honors Thesis"},
    {    regex:   /FREN-UA(&nbsp;)998/g, replacement:  "Independent Study"},
    {    regex:   /AHSEM-UA(&nbsp;)235/g, replacement:  "History and the Novel"},
    {    regex:   /AHSEM-UA(&nbsp;)247/g, replacement:  "Assessing Epidemiological Literature Public Health: What AELs you?\""},
    {    regex:   /AHSEM-UA(&nbsp;)257/g, replacement:  "Religious Skepticism from Ancient Greece to Medieval Islam"},
    {    regex:   /AHSEM-UA(&nbsp;)258/g, replacement:  "The Crisis of Europe"},
    {    regex:   /AHSEM-UA(&nbsp;)259/g, replacement:  "Metapatterns and Big History"},
    	{
	    regex: /Bldg:/g,
	    replacement: "Building: "
	},
	{
	    regex: /CIWW/g,
	    replacement: "<a href=\"https://goo.gl/maps/eTwn5c2fky62\">Warren Weaver Hall</a>"
	},
	{
	    regex: /SILV/g,
	    replacement: "<a href=\"https://goo.gl/maps/oRCqugARiqr\"> Silver Building </a>"
	},
	{
	    regex: /Room:/g,
	    replacement: "Room: "
	},
	{
	    regex: /Loc:/g,
	    replacement: "Location: "
	},
	{
	    regex: /<span>Mo<\/span>/g,
	    replacement: "<span> Monday </span>"
	},
	{
	    regex: /MoWe/g,
	    replacement: "Monday, Wednesday"
	},
	{
	    regex: /TuTh/g,
	    replacement: "Tuesday, Thursday"
	},
	{
	    regex: /MATH-UA(&nbsp;)349/g,
	    replacement: "Honors Algebra II"
	},
];

setTimeout(() => {
    let body = document.body.innerHTML;
    replacements.map(r => {
	body = body.replace(r.regex, r.replacement);
    })

    document.body.innerHTML = body;
    
}, 3000);
